#!/bin/bash
if [[ $EUID -ne 0 ]]; then
echo "You will now be asked for your password, this is needed for updating MiniUtils"
sudo $0
exit 0
fi
echo "Checking for updates..."
mkdir -p /temp/MiniUpdater
wget -q -O "/temp/MiniUpdater/repo.zip" "https://github.com/JoshCoder26/MiniUtils/archive/main.zip"
unzip -q "/temp/MiniUpdater/repo.zip" -p "/temp/MiniUpdater"
